export interface SqacTrackerItem {
  id: string;
  user_id: string;
  wid: string;
  site: string;
  band: string;
  connected: string | null;
  audit: string | null;
  dt: string | null;
  sqac_status: string;
  sqac_remark: string;
  created_at: string;
  type_of_work: string;
  tac: string;
  city: string;
  band_impact: string;
}

export interface DataKpiStatistic4g {
  kpi_index: number;
  kpi_name: string;
  unit: string;
  day1_val: string;
  day2_val: string;
  day3_val: string;
  average: string;
  target: string;
  delta: string;
  growth_val: string;
  growth_dir: string;
  remark: string;
  "RRC Est Success Rate (%)": string;
  Band: string;
  BandCity: string;
  "CQI Average": string;
  "CSFB (%)": string;
  "Call Setup Success Rate (%)": string;
  City: string;
  "E-RAB Drop Rate (%)": string;
  "E-RAB Success Rate (%)": string;
  "Intra Freq LTE HO (%)": string;
  "Inter Freq LTE HO (%)": string;
  SE2: string;
  "Uplink RSSI (dBm)": string;
  "DCR (%)": string;
  "HOSR (%)": string;
  "ICM BAND (0-5)": string;
  "SDSR (%)": string;
  "TBF COMPLETION SR (%)": string;
  "TBF DL EST SR (%)": string;
  "TBF UL EST SR (%)": string;
  Date: string;
  Calendar_Day: string;
  "Utilization (%)": string;
  "BH Traffic (Erl)": string;
  "Payload (MB)": string;
  sort: number;
  "Site Avail (%)": number;
  "EDGE DL Payload (GByte)": string;
  "EDGE UL Payload (GByte)": string;
  "Day-1 Before": string;
  "Day-2 Before": string;
  "Day-3 Before": string;
  "Day-1 After": string;
  "Day-2 After": string;
  "Day-3 After": string;
  "Average Before": string;
  "Average After": string;
  KPI: string;
  Growth: string;
  Result: string;
}
