import { sql } from "drizzle-orm";
import { doublePrecision, integer, pgTable, primaryKey, timestamp, varchar } from "drizzle-orm/pg-core";

export const dy2G = pgTable(
  "dy2G",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("Managed Element", { length: 100 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    cssrVoiceNum: doublePrecision("cssr_voice_num"),
    cssrVoiceDenum: doublePrecision("cssr_voice_denum"),
    numHosrNfj: doublePrecision("Num HOSR NFJ"),
    denumHosrNfj: doublePrecision("Denum HOSR NFJ"),
    numSdsrNfj: doublePrecision("Num SDSR NFJ"),
    denumSdsrNfj: doublePrecision("Denum SDSR NFJ"),
    numTchDropNfj: doublePrecision("Num TCH Drop NFJ"),
    denumTchDropNfj: doublePrecision("Denum TCH Drop NFJ"),
    numTbfDlEstSrNfj: doublePrecision("Num TBF DL Est SR NFJ"),
    denumTbfDlEstSrNfj: doublePrecision("Denum TBF DL Est SR NFJ"),
    numTbfUlEstSrNfj: doublePrecision("Num TBF UL Est SR NFJ"),
    denumTbfUlEstSrNfj: doublePrecision("Denum TBF UL Est SR NFJ"),
    tbfCompleteNumFix: doublePrecision("tbf_complete_num_FIX"),
    tbfCompleteDenumFix: doublePrecision("tbf_complete_denum_fix"),
    "tchTraffic (erlang)Nfj": doublePrecision("TCH Traffic (Erlang) NFJ"),
    numTchBlockNfj: doublePrecision("Num TCH Block NFJ"),
    denumTchBlokNfj: doublePrecision("Denum TCH Blok NFJ"),
    "sdcchTraffic (erlang)Nfj": doublePrecision("SDCCH Traffic (Erlang) NFJ"),
    numSdcchBlockNfj: doublePrecision("Num SDCCH Block NFJ"),
    denumSdcchBlockNfj: doublePrecision("Denum SDCCH Block NFJ"),
    numTchAvailabilityNfj: doublePrecision("Num TCH Availability NFJ"),
    denumTchAvailabilityNfj: doublePrecision("Denum TCH Availability NFJ"),
    sdcchAvailabilityNum: doublePrecision("SDCCH_Availability_num"),
    sdcchAvailabilityDenum: doublePrecision("SDCCH_Availability_denum"),
    "gprsDlThroughput (kbps)Nfj": doublePrecision("GPRS DL Throughput (Kbps) NFJ"),
    "edgeDlThroughput (kbps)Nfj": doublePrecision("EDGE DL Throughput (Kbps) NFJ"),
    gprsPayloadDlMbyte: doublePrecision("gprs_payload_dl_mbyte"),
    gprsPayloadUlMbyte: doublePrecision("gprs_payload_ul_mbyte"),
    gprsPayloadMbyte: doublePrecision("gprs_payload_mbyte"),
    edgePayloadDlMbyte: doublePrecision("edge_payload_dl_mbyte"),
    edgePayloadUlMbyte: doublePrecision("edge_payload_ul_mbyte"),
    edgePayloadMbyte: doublePrecision("edge_payload_mbyte"),
    tchAssignmentSuccessRateNum: doublePrecision("TCH assignment success rate-Num"),
    tchAssignmentSuccessRateDenum: doublePrecision("TCH assignment success rate-Denum"),
    sdcchDropRateNum: doublePrecision("SDCCH_Drop_Rate_num"),
    sdcchDropRateDenum: doublePrecision("SDCCH_Drop_Rate_denum"),
    u31DlQual05Num: doublePrecision("U31_DL Qual 0-5 num"),
    u31DlQual05Denum: doublePrecision("U31_DL Qual 0-5 denum"),
    ulQual05Num: doublePrecision("UL Qual 0-5 num"),
    ulQual05Denum: doublePrecision("UL Qual 0-5 denum"),
    nfIcmBand13Num: doublePrecision("NF_ICM Band 1-3_num"),
    nfIcmBand13Denum: doublePrecision("NF_ICM Band 1-3_denum"),
    nfIcmBand35Num: doublePrecision("NF_ICM Band 3-5_num"),
    nfIcmBand35Denum: doublePrecision("NF_ICM Band 3-5_denum"),
    nfIcmBand45Num: doublePrecision("NF_ICM Band 4-5_num"),
    nfIcmBand45Denum: doublePrecision("NF_ICM Band 4-5_denum"),
    nfIcmBand5Num: doublePrecision("NF_ICM Band 5_num"),
    nfIcmBand5Denum: doublePrecision("NF_ICM Band 5_denum"),
    "averageTimeOfCallAccess(ms)": doublePrecision("Average time of call access(ms)"),
    "averageTimeOfCallSetup(ms)": doublePrecision("Average time of call setup(ms)"),
    numberOfCsfbServiceFastreturnToLte: doublePrecision("Number of CSFB service fastreturn to LTE"),
    numIcmInterferenceNfj: doublePrecision("Num ICM INTERFERENCE NFJ"),
    denumIcmInterferenceNfj: doublePrecision("Denum ICM INTERFERENCE NFJ"),
    mosDl: doublePrecision("MOS_DL"),
    mosUl: doublePrecision("MOS_UL"),
    numberOfSrvccServiceFastreturnToLte: doublePrecision("Number of SRVCC service fastreturn to LTE"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    numberOfTrXs: doublePrecision("Number of TRXs"),
    numberOfAbisPsPagingMessages: doublePrecision("Number of Abis PS paging messages"),
    numberOfAbisInterfacePagingCommandMessages: doublePrecision("Number of Abis interface paging command messages"),
    ccsrVoiceNum: doublePrecision("ccsr_voice_num"),
    ccsrVoiceDen: doublePrecision("ccsr_voice_den"),
    tchTrafficFr: doublePrecision("tch_traffic_fr"),
    tchTrafficHr: doublePrecision("tch_traffic_hr"),
    tchDefine: doublePrecision("tch_define"),
    hrPenetrationNum: doublePrecision("hr_penetration_num"),
    hrPenetrationDenum: doublePrecision("hr_penetration_denum"),
    averageNumberOfAvailableSdccHs: doublePrecision("Average number of available SDCCHs"),
    numberOfAbisDeleteIndMessages: doublePrecision("Number of ABIS_DELETE_IND messages"),
    radioUtilizationNum: doublePrecision("Radio Utilization Num"),
    radioUtilizationDenum: doublePrecision("Radio Utilization Denum"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "sdToTchSuccessRate (%)Num": doublePrecision("SD to TCH Success Rate (%)_num"),
    "sdToTchSuccessRate (%)Denum": doublePrecision("SD to TCH Success Rate (%)_denum"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    dataIntegrity: doublePrecision("Data Integrity"),
  },
  (table) => [
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "dy2G_pkey",
    }),
  ],
);

export const dy4G = pgTable(
  "dy4G",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("Managed Element", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 100 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    kpiNumRrcSetupSr: doublePrecision("KPI Num RRC Setup SR"),
    kpiDenumRrcSetupSr: doublePrecision("KPI Denum RRC Setup SR"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    kpiNumCssr: doublePrecision("KPI Num CSSR"),
    kpiDenumCssr: doublePrecision("KPI Denum CSSR"),
    kpiNumServiceDropRate: doublePrecision("KPI Num Service Drop Rate"),
    kpiDenumServiceDropRate: doublePrecision("KPI Denum Service Drop Rate"),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    kpiNumCsfbSr: doublePrecision("KPI Num CSFB SR"),
    kpiDenumCsfbSr: doublePrecision("KPI Denum CSFB SR"),
    "kpiDlTrafficVolume (mByte)": doublePrecision("KPI DL Traffic Volume (MByte)"),
    "kpiUlTrafficVolume (mByte)": doublePrecision("KPI UL Traffic Volume (MByte)"),
    "kpi4GPayload (mByte)": doublePrecision("KPI 4G Payload (MByte)"),
    averageDlActiveUserNumber: doublePrecision("Average DL Active User Number"),
    averageActiveUserNumberOnUserPlane: doublePrecision("Average Active User Number on User Plane"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    meanNumberOfRrcConnectionUser: doublePrecision("Mean Number of RRC Connection User"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    kpiCellAvailabilityNum: doublePrecision("KPI Cell Availability Num"),
    kpiCellAvailabilityDenum: doublePrecision("KPI Cell Availability Denum"),
    "numDlPrbUtilization (%)NfjRev": doublePrecision("Num DL PRB Utilization (%) NFJ_Rev"),
    "denumDlPrbUtilization (%)NfjRev": doublePrecision("Denum DL PRB Utilization (%) NFJ_Rev"),
    "numUlPrbUtilization (%)NfjRev": doublePrecision("Num UL PRB Utilization (%) NFJ_Rev"),
    "denumUlPrbUtilization (%)NfjRev": doublePrecision("Denum UL PRB Utilization (%) NFJ_Rev"),
    numAverageCqiRev: doublePrecision("Num Average CQI_Rev"),
    denumAverageCqiRev: doublePrecision("Denum Average CQI_Rev"),
    revSeNumDl: doublePrecision("rev_SE_NUM_DL"),
    revSeDenumDl: doublePrecision("rev_SE_DENUM_DL"),
    revSeNumUl: doublePrecision("rev_SE_NUM_UL"),
    revSeDenumUl: doublePrecision("rev_SE_DENUM_UL"),
    "volteTraffic (erl)Tjh": doublePrecision("volte_Traffic (Erl)_TJH"),
    "volteDlVolumeQci1(mByte)TjhRev": doublePrecision("volte_DL Volume_QCI1(MByte)_TJH_Rev"),
    "volteUlVolumeQci1(mByte)Tjh": doublePrecision("volte_UL Volume_QCI1(MByte)_TJH"),
    "volteCallSetupSr (qci1Qci5)V3Num": doublePrecision("volte_Call Setup SR (QCI1_QCI5)_V3 Num"),
    "volteCallSetupSr (qci1Qci5)V3Denum": doublePrecision("volte_Call Setup SR (QCI1_QCI5)_V3 Denum"),
    "numVolteCallDropRate (%)TjhRev": doublePrecision("Num_volte_Call Drop Rate (%)_TJH_Rev"),
    "denumVolteCallDropRate (%)TjhRev": doublePrecision("Denum_volte_Call Drop Rate (%)_TJH_Rev"),
    "volteSrvccHandoverSr (lteUmts)Num": doublePrecision("volte_SRVCC_Handover SR (LTE_UMTS)_Num"),
    "volteSrvccHandoverSr (lteUmts)Denum": doublePrecision("volte_SRVCC_Handover SR (LTE_UMTS)_Denum"),
    "volteSrvccHandoverSr (lteGsm)Num": doublePrecision("volte_SRVCC_Handover SR (LTE_GSM)_Num"),
    "volteSrvccHandoverSr (lteGsm)Denum": doublePrecision("volte_SRVCC_Handover SR (LTE_GSM)_Denum"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "kpiPagingCongestionRate (%)": doublePrecision("KPI Paging Congestion Rate (%)"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    numIntraFreqHo: doublePrecision("Num Intra Freq HO"),
    denumIntraFreqHo: doublePrecision("Denum Intra Freq HO"),
    kpiPagingNumberFromS1: doublePrecision("KPI Paging Number from S1"),
    numberOfPagingRecordsDiscardedAtTheENodeB: doublePrecision("Number of Paging Records Discarded at the eNodeB"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    numRatioOfCqi10Rev: doublePrecision("Num Ratio of CQI10_Rev"),
    denumRatioOfCqi10Rev: doublePrecision("Denum Ratio of CQI10_Rev"),
    kpiTheRatioOfCqi7MonitorNum: doublePrecision("KPI The Ratio of CQI7 Monitor Num"),
    kpiTheRatioOfCqi7MonitorDenum: doublePrecision("KPI The Ratio of CQI7 Monitor Denum"),
    "spectralEfficiencyNew (drbSrbPsdch)": doublePrecision("Spectral Efficiency New (DRB_SRB_PSDCH)"),
    newActiveUsersRnpRev: doublePrecision("New Active Users RNP_Rev"),
    attemptedOutgoingHandoversExecutionOverX2: doublePrecision("Attempted Outgoing Handovers Execution Over X2"),
    successfulOutgoingHandoversExecutionOverX2: doublePrecision("Successful Outgoing Handovers Execution Over X2"),
    attemptedOutgoingHandoversExecutionOverS1: doublePrecision("Attempted Outgoing Handovers Execution Over S1"),
    successfulOutgoingHandoversExecutionOverS1: doublePrecision("Successful Outgoing Handovers Execution Over S1"),
    caPayloadRev: doublePrecision("CA Payload_Rev"),
    numDlAverageMcs: doublePrecision("Num DL Average MCS"),
    denumDlAverageMcs: doublePrecision("Denum DL Average MCS"),
    numUlAverageMcs: doublePrecision("Num UL Average MCS"),
    denumUlAverageMcs: doublePrecision("Denum UL Average MCS"),
    kpiDlQpskModulationSchemeUsageNum: doublePrecision("KPI DL QPSK Modulation Scheme Usage Num"),
    kpiDlQpskModulationSchemeUsageDenum: doublePrecision("KPI DL QPSK Modulation Scheme Usage Denum"),
    kpiUlQpskModulationSchemeUsageNum: doublePrecision("KPI UL QPSK Modulation Scheme Usage Num"),
    kpiUlQpskModulationSchemeUsageDenum: doublePrecision("KPI UL QPSK Modulation Scheme Usage Denum"),
    "volteERabSetupSr (qci1Qci5)V2Num": doublePrecision("volte_E-RAB Setup SR (QCI1_QCI5)_V2 Num"),
    "volteERabSetupSr (qci1Qci5)V2Denum": doublePrecision("volte_E-RAB Setup SR (QCI1_QCI5)_V2 Denum"),
    "volteCallDropRateMme (%)NumTjh": doublePrecision("volte_Call Drop Rate_MME (%)_num_TJH"),
    "volteCallDropRateMme (%)DenumTjh": doublePrecision("volte_Call Drop Rate_MME (%)_Denum_TJH"),
    volteUserOutgoingIntraFreqHosrNum: doublePrecision("volte_User Outgoing Intra-Freq HOSR_Num"),
    "volteUserOutgoingIntraFreqHosr (%)DenumTjh": doublePrecision("volte_User Outgoing Intra-Freq HOSR (%)_denum_TJH"),
    "volteUserOutgoingInterFreqHosr (%)NumTjh": doublePrecision("volte_User Outgoing Inter-Freq HOSR (%)_num_TJH"),
    "volteUserOutgoingInterFreqHosr (%)DenumTjh": doublePrecision("volte_User Outgoing Inter-Freq HOSR (%)_denum_TJH"),
    averageSinr: doublePrecision("Average SINR"),
    badSinr: doublePrecision("Bad_SINR"),
    goodSinr: doublePrecision("Good_SINR"),
    "numberOfSuccessfulOutgoingInterRat(lteUtran)": doublePrecision(
      "Number of Successful Outgoing inter-RAT(LTE_UTRAN)",
    ),
    "numberOfSuccessfulOutgoingInterRat(lteGsm)": doublePrecision("Number of Successful Outgoing inter-RAT(LTE_GSM)"),
    "numERabDropRate (%)NfjRev": doublePrecision("Num E-RAB Drop Rate (%) NFJ_Rev"),
    "denumERabDropRate (%)NfjRev": doublePrecision("Denum E-RAB Drop Rate (%) NFJ_Rev"),
    csfbReleaseSuccessRateNum: doublePrecision("CSFB release success rate Num"),
    csfbReleaseSuccessRateDeNum: doublePrecision("CSFB release success rate DENum"),
    avgPrbUsageDlRelactuserdlModifyRev: doublePrecision("avg_prb_usage_dl_relactuserdl Modify_rev"),
    avgPrbUsageUlRelactuserdl: doublePrecision("avg_prb_usage_ul_relactuserdl"),
    ulEmi38Num: doublePrecision("UL_EMI_3_8_NUM"),
    ulEmi38Denum: doublePrecision("UL_EMI_3_8_DENUM"),
    voLteSrvccHandoverSrLteGsmNumTjh: doublePrecision("VoLTE_SRVCC_Handover_SR_LTE_GSM_num_TJH"),
    voLteSrvccHandoverSrLteGsmDenumTjh: doublePrecision("VoLTE_SRVCC_Handover_SR_LTE_GSM_denum_TJH"),
    numberOfInitialERabSetupFailuresDueToTransport: doublePrecision(
      "Number of Initial E-RAB Setup Failures due to Transport",
    ),
    numberOfAdditionalERabSetupFailuresDueToTransport: doublePrecision(
      "Number of Additional E-RAB Setup Failures due to Transport",
    ),
    voLteDlPoorQualityEmiDistributionHz: doublePrecision("VoLTE DL poor-quality EMI_distribution_HZ"),
    seNumOkRev: doublePrecision("SE_NUM_ok_rev"),
    seDenumOkRev: doublePrecision("se_denum_ok_rev"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    prbNumberAvailableOnUl: doublePrecision("PRB Number Available on UL"),
    prbNumberAvailableOnDl: doublePrecision("PRB Number Available on DL"),
    newActiveUsersRnpAmq: doublePrecision("New Active Users rnp AMQ"),
  },
  (table) => [
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "dy4GTdd_pkey",
    }),
  ],
);

export const dy4G2 = pgTable(
  "dy4G_2",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "dy4G_2_pkey",
    }),
  ],
);

export const hy4G2 = pgTable(
  "hy4G_2",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "hy4G_2_pkey",
    }),
  ],
);

export const dy2G2 = pgTable(
  "dy2G_2",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
  },
  (table) => [
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "dy2G_2_pkey",
    }),
  ],
);

export const hy2G2 = pgTable(
  "hy2G_2",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
  },
  (table) => [
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "hy2G_2_pkey",
    }),
  ],
);

export const dataSidNopKabupaten = pgTable("data_sid_nop_kabupaten", {
  siteId: varchar("Site ID", { length: 6 }).primaryKey().notNull(),
  area: varchar("AREA", { length: 20 }),
  nop: varchar("NOP", { length: 50 }),
  kabupaten: varchar("KABUPATEN", { length: 100 }),
});

export const dataSidActivity = pgTable("data_sid_activity", {
  siteId: varchar("Site ID", { length: 6 }).primaryKey().notNull(),
  activity1: varchar("Activity_1", { length: 20 }),
  activity2: varchar("Activity_2", { length: 20 }),
  activity3: varchar("Activity_3", { length: 20 }),
  activity4: varchar("Activity_4", { length: 20 }),
  activity5: varchar("Activity_5", { length: 20 }),
  activity6: varchar("Activity_6", { length: 20 }),
  activity7: varchar("Activity_7", { length: 20 }),
  activity8: varchar("Activity_8", { length: 20 }),
  activity9: varchar("Activity_9", { length: 20 }),
  activity10: varchar("Activity_10", { length: 20 }),
});

export const tbBatch1PowerUpgrade = pgTable("tb_batch1_power_upgrade", {
  area: varchar("AREA", { length: 255 }),
  nop: varchar("NOP", { length: 255 }),
  kabupaten: varchar("KABUPATEN", { length: 255 }),
  concat: varchar({ length: 255 }),
  idxSiteCell: varchar("idx_site_cell", { length: 255 }),
  idxSiteidSector: varchar("idx_siteid_sector", { length: 255 }),
  idxSiteid: varchar("idx_siteid", { length: 255 }),
  subnetWorkId: integer("SubnetWork ID"),
  managedElementId: integer("ManagedElement ID"),
  eNodeBid: integer(),
  cellId: integer(),
  band: varchar("BAND", { length: 255 }),
  batch: varchar("Batch", { length: 255 }),
  remarkPower: varchar("REMARK_POWER", { length: 255 }),
  cellExecute: varchar("Cell Execute", { length: 255 }),
  sectorExecute: varchar("Sector Execute", { length: 255 }),
  siteExecute: varchar("Site Execute", { length: 255 }),
});
