import { sql } from "drizzle-orm";
import { doublePrecision, index, integer, pgTable, primaryKey, timestamp, varchar } from "drizzle-orm/pg-core";

export const dataSidActivity = pgTable("data_sid_activity", {
  siteId: varchar("Site ID", { length: 6 }).primaryKey().notNull(),
  activity1: varchar("Activity_1", { length: 20 }),
  activity2: varchar("Activity_2", { length: 20 }),
  activity3: varchar("Activity_3", { length: 20 }),
  activity4: varchar("Activity_4", { length: 20 }),
  activity5: varchar("Activity_5", { length: 20 }),
  activity6: varchar("Activity_6", { length: 20 }),
  activity7: varchar("Activity_7", { length: 20 }),
  activity8: varchar("Activity_8", { length: 20 }),
  activity9: varchar("Activity_9", { length: 20 }),
  activity10: varchar("Activity_10", { length: 20 }),
});

export const dataSidNopKabupaten = pgTable(
  "data_sid_nop_kabupaten",
  {
    siteId: varchar("Site ID", { length: 6 }).primaryKey().notNull(),
    area: varchar("AREA", { length: 20 }),
    nop: varchar("NOP", { length: 50 }),
    kabupaten: varchar("KABUPATEN", { length: 100 }),
  },
  (table) => [index("idx_data_sid_site").using("btree", table.siteId.asc().nullsLast().op("text_ops"))],
);

export const tbBatch1PowerUpgrade = pgTable(
  "tb_batch1_power_upgrade",
  {
    area: varchar("AREA", { length: 255 }),
    nop: varchar("NOP", { length: 255 }),
    kabupaten: varchar("KABUPATEN", { length: 255 }),
    idxSubMeNodebCi: varchar("idx_sub_me_nodeb_ci", { length: 255 }),
    idxSiteCell: varchar("idx_site_cell", { length: 255 }),
    idxSiteidSector: varchar("idx_siteid_sector", { length: 255 }),
    idxSiteidSectorRci: varchar("idx_siteid_sector_rci", { length: 255 }),
    idxSiteid: varchar("idx_siteid", { length: 255 }),
    subnetWorkId: integer("SubnetWork ID"),
    managedElementId: integer("ManagedElement ID"),
    eNodeBid: integer(),
    cellId: integer(),
    band: varchar("BAND", { length: 255 }),
    batch: varchar("Batch", { length: 255 }),
    remarkPower: varchar("REMARK_POWER", { length: 255 }),
    cellExecute: varchar("Cell Execute", { length: 255 }),
    sectorExecute: varchar("Sector Execute", { length: 255 }),
    siteExecute: varchar("Site Execute", { length: 255 }),
    dateExec: timestamp("Date Exec", { precision: 6, mode: "string" }),
  },
  (table) => [
    index("idx_tb_batch_join").using(
      "btree",
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("int4_ops"),
      table.eNodeBid.asc().nullsLast().op("int4_ops"),
      table.cellId.asc().nullsLast().op("int4_ops"),
    ),
  ],
);

export const hy2G2 = pgTable(
  "hy2G_2",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
    sdToTchNumAmq: doublePrecision("SD_TO_TCH_Num_AMQ"),
    sdToTchDenumAmq: doublePrecision("SD_TO_TCH_Denum_AMQ"),
    sdcchDropRateNum: doublePrecision("SDCCH_Drop_Rate_num"),
    sdcchDropRateDenum: doublePrecision("SDCCH_Drop_Rate_denum"),
    sdcchAvailabilityNum: doublePrecision("SDCCH_Availability_num"),
    sdcchAvailabilityDenum: doublePrecision("SDCCH_Availability_denum"),
    nfIcmBand13Num: doublePrecision("NF_ICM Band 1-3_num"),
    nfIcmBand13Denum: doublePrecision("NF_ICM Band 1-3_denum"),
    nfIcmBand45Num: doublePrecision("NF_ICM Band 4-5_num"),
    nfIcmBand45Denum: doublePrecision("NF_ICM Band 4-5_denum"),
  },
  (table) => [
    index("idx_hy2g_time_btname").using(
      "btree",
      table.beginTime.asc().nullsLast().op("text_ops"),
      table.btsName.asc().nullsLast().op("text_ops"),
    ),
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "hy2G_2_pkey",
    }),
  ],
);

export const dy2G = pgTable(
  "dy2G",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
    sdToTchNumAmq: doublePrecision("SD_TO_TCH_Num_AMQ"),
    sdToTchDenumAmq: doublePrecision("SD_TO_TCH_Denum_AMQ"),
    sdcchDropRateNum: doublePrecision("SDCCH_Drop_Rate_num"),
    sdcchDropRateDenum: doublePrecision("SDCCH_Drop_Rate_denum"),
    sdcchAvailabilityNum: doublePrecision("SDCCH_Availability_num"),
    sdcchAvailabilityDenum: doublePrecision("SDCCH_Availability_denum"),
    nfIcmBand13Num: doublePrecision("NF_ICM Band 1-3_num"),
    nfIcmBand13Denum: doublePrecision("NF_ICM Band 1-3_denum"),
    nfIcmBand45Num: doublePrecision("NF_ICM Band 4-5_num"),
    nfIcmBand45Denum: doublePrecision("NF_ICM Band 4-5_denum"),
  },
  (table) => [
    index("idx_dy2G_3_time_btname").using(
      "btree",
      table.beginTime.asc().nullsLast().op("timestamp_ops"),
      table.btsName.asc().nullsLast().op("timestamp_ops"),
    ),
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "dy2G_3_pkey",
    }),
  ],
);

export const dy2G2 = pgTable(
  "dy2G_2",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
    sdToTchNumAmq: doublePrecision("SD_TO_TCH_Num_AMQ"),
    sdToTchDenumAmq: doublePrecision("SD_TO_TCH_Denum_AMQ"),
    sdcchDropRateNum: doublePrecision("SDCCH_Drop_Rate_num"),
    sdcchDropRateDenum: doublePrecision("SDCCH_Drop_Rate_denum"),
    sdcchAvailabilityNum: doublePrecision("SDCCH_Availability_num"),
    sdcchAvailabilityDenum: doublePrecision("SDCCH_Availability_denum"),
    nfIcmBand13Num: doublePrecision("NF_ICM Band 1-3_num"),
    nfIcmBand13Denum: doublePrecision("NF_ICM Band 1-3_denum"),
    nfIcmBand45Num: doublePrecision("NF_ICM Band 4-5_num"),
    nfIcmBand45Denum: doublePrecision("NF_ICM Band 4-5_denum"),
  },
  (table) => [
    index("idx_dy2g_time_btname").using(
      "btree",
      table.beginTime.asc().nullsLast().op("text_ops"),
      table.btsName.asc().nullsLast().op("text_ops"),
    ),
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "dy2G_2_pkey",
    }),
  ],
);

export const hy2G = pgTable(
  "hy2G",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 255 }),
    siteId: integer("SITE ID").notNull(),
    siteName: varchar("SITE Name", { length: 255 }),
    btsId: integer("BTS ID").notNull(),
    btsName: varchar("BTS Name", { length: 255 }),
    nodeBName: varchar("NodeB Name", { length: 255 }),
    locationAreaCode: integer("Location Area Code").notNull(),
    cellIdentity: integer("Cell Identity").notNull(),
    "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
    "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
    "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
    "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
    "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
    "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
    "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
    "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
    "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
    "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
    "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
    numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
    denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
    tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
    tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
    tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
    tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
    hosrNumOno: doublePrecision("HOSR_num_ono"),
    hosrDenumOno: doublePrecision("HOSR_denum_ono"),
    sdsrNumOno: doublePrecision("SDSR_num_ono"),
    sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
    tbfDlEstNumOno: doublePrecision("TBF_DL_Est_Num_ono"),
    tbfDlEstDenumOno: doublePrecision("TBF_DL_Est_denum_ono"),
    tbfCompNumOno: doublePrecision("TBF_Comp_num_ono"),
    tbfCompDenumOno: doublePrecision("TBF_Comp_denum_ono"),
    "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
    sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
    sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
    numberOfTrx: doublePrecision("Number of TRX"),
    numberOfTch: doublePrecision("Number of TCH"),
    numberOfSdcch: doublePrecision("Number of SDCCH"),
    numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
    numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
    numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
    denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
    "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
    numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
    denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
    "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
    numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
    denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
    "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
    tbfUlEstNumOno: doublePrecision("TBF_UL_Est_num_ono"),
    tbfUlEstDenumOno: doublePrecision("TBF_UL_Est_denum_ono"),
    "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
    "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
    "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
    "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
    "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
    numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
    numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
    dlEmiOno: doublePrecision("DL_EMI_Ono"),
    dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
    dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
    ulEmiOno: doublePrecision("UL_EMI_Ono"),
    ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
    ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
    "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
    "pdtchCongestionRate (%)Num": doublePrecision("PDTCH Congestion Rate (%)_num"),
    "pdtchCongestionRate (%)Denum": doublePrecision("PDTCH Congestion Rate (%)_denum"),
    "pdtchCongestionRate(%)": doublePrecision("PDTCH congestion rate(%)"),
    sdToTchNumAmq: doublePrecision("SD_TO_TCH_Num_AMQ"),
    sdToTchDenumAmq: doublePrecision("SD_TO_TCH_Denum_AMQ"),
    sdcchDropRateNum: doublePrecision("SDCCH_Drop_Rate_num"),
    sdcchDropRateDenum: doublePrecision("SDCCH_Drop_Rate_denum"),
    sdcchAvailabilityNum: doublePrecision("SDCCH_Availability_num"),
    sdcchAvailabilityDenum: doublePrecision("SDCCH_Availability_denum"),
    nfIcmBand13Num: doublePrecision("NF_ICM Band 1-3_num"),
    nfIcmBand13Denum: doublePrecision("NF_ICM Band 1-3_denum"),
    nfIcmBand45Num: doublePrecision("NF_ICM Band 4-5_num"),
    nfIcmBand45Denum: doublePrecision("NF_ICM Band 4-5_denum"),
  },
  (table) => [
    index("idx_hy2g3_time_btname").using(
      "btree",
      table.beginTime.asc().nullsLast().op("timestamp_ops"),
      table.btsName.asc().nullsLast().op("timestamp_ops"),
    ),
    primaryKey({
      columns: [
        table.beginTime,
        table.subnetWorkId,
        table.managedElementId,
        table.siteId,
        table.btsId,
        table.locationAreaCode,
        table.cellIdentity,
      ],
      name: "hy2G_pkey",
    }),
  ],
);

export const hy4G = pgTable(
  "hy4G",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    index("idx_hy4g3_main").using(
      "btree",
      table.beginTime.asc().nullsLast().op("int4_ops"),
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("timestamp_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("timestamp_ops"),
    ),
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "hy4G_pkey",
    }),
  ],
);

export const dy4G2 = pgTable(
  "dy4G_2",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    index("idx_dy4g_main").using(
      "btree",
      table.beginTime.asc().nullsLast().op("int4_ops"),
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("int4_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("int4_ops"),
    ),
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "dy4G_2_pkey",
    }),
  ],
);

export const dy4G = pgTable(
  "dy4G",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    index("idx_dy4G_3_main").using(
      "btree",
      table.beginTime.asc().nullsLast().op("int4_ops"),
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("timestamp_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("timestamp_ops"),
    ),
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "dy4G_3_pkey",
    }),
  ],
);

export const hy4G2 = pgTable(
  "hy4G_2",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    managedElement: varchar("ManagedElement", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: integer("eNodeBId").notNull(),
    cellId: integer().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    csfbReleaseNum: doublePrecision("CSFB release num"),
    csfbReleaseDenum: doublePrecision("CSFB release denum"),
    csfbReleaseSuccessRate: doublePrecision("CSFB release success rate"),
    kpiS1SignalConnectionEstSrNum: doublePrecision("KPI S1-Signal Connection Est SR Num"),
    kpiS1SignalConnectionEstSrDenum: doublePrecision("KPI S1-Signal Connection Est SR Denum"),
    "kpiS1SignalConnectionEstSr (%)": doublePrecision("KPI S1-Signal Connection Est SR (%)"),
  },
  (table) => [
    index("idx_hy4g_main").using(
      "btree",
      table.beginTime.asc().nullsLast().op("int4_ops"),
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("int4_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("int4_ops"),
    ),
    primaryKey({
      columns: [table.beginTime, table.subnetWorkId, table.managedElementId, table.eNodeBid, table.cellId],
      name: "hy4G_2_pkey",
    }),
  ],
);
