// biome-ignore assist/source/organizeImports: <none>
import { pgTable, index, timestamp, doublePrecision, varchar, integer, time } from "drizzle-orm/pg-core";

export const sulwCellList4Gv3 = pgTable("SulwCellList4Gv3", {
  week: varchar("Week", { length: 255 }),
  nop: varchar("NOP", { length: 255 }),
  kabupaten: varchar("KABUPATEN", { length: 255 }),
  idxSubMeEnodebCell: varchar("idx_sub_me_enodeb_cell", {
    length: 255,
  }).notNull(),
  idxSiteCell: varchar("idx_site_cell", { length: 255 }),
  idxSiteidSector: varchar("idx_siteid_sector", { length: 255 }),
  siteId: varchar("Site ID", { length: 255 }),
  subnetwork: integer("Subnetwork"),
  managedElement: integer("ManagedElement"),
  eNodeB: integer(),
  cell: integer("Cell"),
  band: varchar("BAND", { length: 255 }),
  powerCellExecuted: varchar("Power - Cell Executed", { length: 255 }),
  powerSiteLevel: varchar("Power - Site Level", { length: 255 }),
  powerSectorExecuted: varchar("Power - Sector Executed", { length: 255 }),
  remarkPower: varchar("Remark - Power", { length: 255 }),
});

export const cellList2G = pgTable("CellList2G", {
  week: varchar("Week", { length: 255 }),
  branch: varchar("Branch", { length: 255 }),
  subnetwork: integer("SUBNETWORK"),
  subnetworkName: varchar("SUBNETWORK Name", { length: 255 }),
  siteId: varchar("Site ID", { length: 255 }),
  site: integer("SITE"),
  siteName: varchar("SITE Name", { length: 255 }),
  sc: varchar("SC", { length: 255 }),
  kabupaten: varchar("KABUPATEN", { length: 255 }),
  rtpo: varchar("RTPO", { length: 255 }),
  bts: integer("BTS"),
  btsName: varchar("BTS NAME", { length: 255 }),
  band: varchar("BAND", { length: 255 }),
  btsName1: varchar("BTS NAME1", { length: 255 }),
  siteid: varchar({ length: 255 }),
  lookup: varchar({ length: 255 }),
  cellCheck: varchar("cell check", { length: 255 }),
  siteCheck: varchar("site check", { length: 255 }),
  siteBand: varchar("site_band", { length: 255 }),
  bandCheck: varchar("band check", { length: 255 }),
  lac: integer("LAC"),
  "ci(ci)": integer("CI(CI)"),
  nop: varchar("NOP", { length: 255 }),
  latitide: doublePrecision("Latitide"),
  longitude: doublePrecision("Longitude"),
});

export const measBdbh4G = pgTable(
  "measBdbh4g",
  {
    beginTime: timestamp("Begin Time", {
      precision: 6,
      mode: "string",
    }).notNull(),
    subnetWorkId: doublePrecision("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 50 }),
    managedElementId: doublePrecision("ManagedElement ID").notNull(),
    "managed element": varchar("Managed Element", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    "eUtran fdd cellName": varchar("E-UTRAN FDD Cell Name", { length: 200 }),
    eNodeBid: doublePrecision().notNull(),
    cellId: doublePrecision().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    x2HoOutNumAmq: doublePrecision("X2 HO Out Num AMQ"),
    x2HoOutDenomAmq: doublePrecision("X2 HO Out Denom AMQ"),
    "x2HoOut (%)Amq": doublePrecision("X2 HO Out (%) AMQ"),
    s1HoOutNumAmq: doublePrecision("S1 HO Out Num AMQ"),
    s1HoOutDenomAmq: doublePrecision("S1 HO Out Denom AMQ"),
    "s1HoOut (%)Amq": doublePrecision("S1 HO Out (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    interFreqX2HoNumAmq: doublePrecision("Inter Freq X2 HO Num AMQ"),
    interFreqX2HoDenumAmq: doublePrecision("Inter Freq X2 HO Denum AMQ"),
    "interFreqX2HoSr_(%)Amq": doublePrecision("Inter Freq X2 HO SR_(%) AMQ"),
    interFreqS1HoNumAmq: doublePrecision("Inter Freq S1 HO Num AMQ"),
    interFreqS1HoDenumAmq: doublePrecision("Inter Freq S1 HO Denum AMQ"),
    "interFreqS1HoSr_(%)Amq": doublePrecision("Inter Freq S1 HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    "maximumCellDlRlcThroughput(mbps)": doublePrecision("Maximum Cell DL RLC Throughput(Mbps)"),
    "maximumCellUlRlcThroughput(mbps)": doublePrecision("Maximum Cell UL RLC Throughput(Mbps)"),
    "maximumCellDlPdcpThroughput(mbps)": doublePrecision("Maximum Cell DL PDCP Throughput(Mbps)"),
    "maximumCellUlPdcpThroughput(mbps)": doublePrecision("Maximum Cell UL PDCP Throughput(Mbps)"),
    "dlPayloadCa_(mByte)Amq": doublePrecision("DL Payload CA_(MByte) AMQ"),
    "ulPayloadCa_(mByte)Amq": doublePrecision("UL Payload CA_(MByte) AMQ"),
    "totalPayloadCa_(mByte)Amq": doublePrecision("Total Payload CA_(MByte) AMQ"),
    dlThroughputCaNumAmq: doublePrecision("DL Throughput CA Num AMQ"),
    dlThroughputCaDenumAmq: doublePrecision("DL Throughput CA Denum AMQ"),
    "dlThroughputCa_(kbps)Amq": doublePrecision("DL Throughput CA_(kbps) AMQ"),
    ulThroughputCaNumAmq: doublePrecision("UL Throughput CA Num AMQ"),
    ulThroughputCaDenumAmq: doublePrecision("UL Throughput CA Denum AMQ"),
    "ulThroughputCa_(kbps)Amq": doublePrecision("UL Throughput CA_(kbps) AMQ"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "u31_[lte]meanRrcConnectedUserNumber": doublePrecision("U31_[LTE]MeanRrcConnectedUserNUmber"),
    u31RatioOfRrcReEstablishment: doublePrecision("U31_Ratio of RRC Re-establishment "),
    "s1SignalConnectionEstablishmentSuccessRate(%)": doublePrecision(
      "S1-Signal Connection Establishment Success Rate(%)",
    ),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    u31AverageDlPdcpSduDelay: doublePrecision("U31_Average DL PDCP SDU Delay"),
    "averageDlIpPacketDelay(ms)": doublePrecision("Average DL IP Packet Delay(ms)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    "u31_[lte]ipLatency": doublePrecision("U31_[LTE]IP Latency"),
    "cellUplinkInitBler(%)": doublePrecision("Cell Uplink Init BLER(%)"),
    "cellDownlinkInitBler(%)": doublePrecision("Cell Downlink Init BLER(%)"),
    averageDlActiveUserNumber: doublePrecision("Average DL Active User Number"),
    "dlAggregatedTimeForIpThroughput(ms)": doublePrecision("DL Aggregated Time For IP Throughput(ms)"),
    "dlAggregatedTime(ms)": doublePrecision("DL Aggregated Time(ms)"),
    prbNumberUsedOnPdschChannel: doublePrecision("PRB Number Used on PDSCH Channel"),
    numberOfCqi11BeUsed: doublePrecision("Number of CQI11 Be Used"),
    numberOfCqi12BeUsed: doublePrecision("Number of CQI12 Be Used"),
    numberOfCqi13BeUsed: doublePrecision("Number of CQI13 Be Used"),
    numberOfCqi14BeUsed: doublePrecision("Number of CQI14 Be Used"),
    numberOfCqi15BeUsed: doublePrecision("Number of CQI15 Be Used"),
    "dlVolumeVoLteQci1_(mByte)Amq": doublePrecision("DL_Volume_VoLTE_QCI1_(MByte) AMQ"),
    "ulVolumeVoLteQci1_(mByte)Amq": doublePrecision("UL_Volume_VoLTE_QCI1_(MByte) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    dlPdcpSduLossQci1NumAmq: doublePrecision("DL_PDCP_SDU_Loss_QCI1_Num AMQ"),
    dlPdcpSduLossQci1DenumAmq: doublePrecision("DL_PDCP_SDU_Loss_QCI1_Denum AMQ"),
    "dlPdcpSduLossQci1_(%)Amq": doublePrecision("DL_PDCP_SDU_Loss_QCI1_(%) AMQ"),
    ulPdcpSduLossQci1NumAmq: doublePrecision("UL_PDCP_SDU_Loss_QCI1_Num AMQ"),
    ulPdcpSduLossQci1DenumAmq: doublePrecision("UL_PDCP_SDU_Loss_QCI1_Denum AMQ"),
    "ulPdcpSduLossQci1_(%)Amq": doublePrecision("UL_PDCP_SDU_Loss_QCI1_(%) AMQ"),
    maxDlActiveUserNumberQci1Amq: doublePrecision("Max_DL_Active_User_Number_QCI1 AMQ"),
    maxUlActiveUserNumberQci1Amq: doublePrecision("Max_UL_Active_User_Number_QCI1 AMQ"),
    avgDlActiveUserNumberQci1Amq: doublePrecision("Avg_DL_Active_User_Number_QCI1 AMQ"),
    avgUlActiveUserNumberQci1Amq: doublePrecision("Avg_UL_Active_User_Number_QCI1 AMQ"),
    maxUserVoLteAmq: doublePrecision("Max_User_VoLTE AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    "averageCpuUtilizationRateOfTheBasebandControlPlane(%)": doublePrecision(
      "Average CPU Utilization Rate of the Baseband Control-Plane(%)",
    ),
    "peakCpuUtilizationRateOfTheBasebandControlPlane(%)": doublePrecision(
      "Peak CPU Utilization Rate of the Baseband Control-Plane(%)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(dueToA2Event)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(Due to A2 event)",
    ),
    "numberOfRedirectionRequestsIntraRat(dueToInterFrequence": doublePrecision(
      "Number of Redirection Requests intra RAT(Due to inter-Frequence",
    ),
    throughputDistributionNum: doublePrecision("Throughput Distribution Num"),
    throughputDistributionDenum: doublePrecision("Throughput Distribution Denum"),
    averageCqiRev: doublePrecision("Average CQI_Rev"),
    numAverageCqiRev: doublePrecision("Num Average CQI_Rev"),
    denumAverageCqiRev: doublePrecision("Denum Average CQI_Rev"),
  },
  (table) => [
    index("idx_begin_time").using("btree", table.beginTime.asc().nullsLast().op("timestamp_ops")),
    index("idx_measbdbh4g_composite").using(
      "btree",
      table.beginTime.asc().nullsLast().op("float8_ops"),
      table.subnetWorkId.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("timestamp_ops"),
      table.managedElementId.asc().nullsLast().op("timestamp_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
    ),
  ],
);

export const cellList4G = pgTable("CellList4G", {
  week: varchar("Week", { length: 255 }),
  siteId: varchar("Site ID", { length: 255 }),
  branch: varchar("Branch", { length: 255 }),
  kabupaten: varchar("KABUPATEN", { length: 255 }),
  sc: varchar("SC", { length: 255 }),
  rtpo: varchar("RTPO", { length: 255 }),
  subnetwork: integer("Subnetwork"),
  subnetworkName: varchar("Subnetwork Name", { length: 255 }),
  site: varchar({ length: 255 }),
  managedElement: integer("ManagedElement"),
  managedElementName: varchar("ManagedElement Name", { length: 255 }),
  band: varchar("BAND", { length: 255 }),
  eNodeB: integer(),
  eNodeBName: varchar("eNodeB Name", { length: 255 }),
  cell: integer("Cell"),
  cellName: varchar("Cell Name", { length: 255 }),
  lookup: varchar("LOOKUP", { length: 255 }),
  band1: varchar("BAND1", { length: 255 }),
  site1: varchar({ length: 255 }),
  band2: varchar("BAND2", { length: 255 }),
  bandwidth: varchar({ length: 255 }),
  product: varchar("Product", { length: 255 }),
  cellCheck: doublePrecision("cell check"),
  siteCheck: varchar("site check", { length: 255 }),
  siteBand: varchar("site_band", { length: 255 }),
  bandCheck: varchar("band check", { length: 255 }),
  tac: integer("TAC"),
  nop: varchar("NOP", { length: 255 }),
  latitude: doublePrecision("Latitude"),
  longitude: doublePrecision("Longitude"),
});

export const measDy4G = pgTable(
  "measDy4g",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    subnetWorkId: doublePrecision("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 100 }),
    managedElementId: doublePrecision("ManagedElement ID").notNull(),
    "managed element": varchar("Managed Element", { length: 100 }),
    eNodeBName: varchar("eNodeB Name", { length: 200 }),
    cellName: varchar("Cell Name", { length: 200 }),
    eNodeBid: doublePrecision().notNull(),
    cellId: doublePrecision().notNull(),
    "dlTrafficVolume (mByte)Amq": doublePrecision("DL Traffic Volume (MByte) AMQ"),
    "ulTrafficVolume (mByte)Amq": doublePrecision("UL Traffic Volume (MByte) AMQ"),
    "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
    cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
    cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
    "cellAvailability4G_(%)": doublePrecision("Cell Availability 4G_(%)"),
    numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
    denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
    "rrcSetupSr (%)Amq": doublePrecision("RRC Setup SR (%) AMQ"),
    numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
    denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
    "eRabSetupSr (%)Amq": doublePrecision("E-RAB Setup SR (%) AMQ"),
    numCssrAmq: doublePrecision("Num CSSR AMQ"),
    denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
    "cssr (%)Amq": doublePrecision("CSSR (%) AMQ"),
    numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
    denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
    "eRabDrop (%)Amq": doublePrecision("E-RAB Drop (%) AMQ"),
    numCsfbSrAmq: doublePrecision("Num CSFB SR AMQ"),
    denumCsfbSrAmq: doublePrecision("Denum CSFB SR AMQ"),
    "csfbSr (%)Amq": doublePrecision("CSFB SR (%) AMQ"),
    numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
    denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
    "ifhoSr (%)Amq": doublePrecision("IFHO SR (%) AMQ"),
    x2HoOutNumAmq: doublePrecision("X2 HO Out Num AMQ"),
    x2HoOutDenomAmq: doublePrecision("X2 HO Out Denom AMQ"),
    "x2HoOut (%)Amq": doublePrecision("X2 HO Out (%) AMQ"),
    s1HoOutNumAmq: doublePrecision("S1 HO Out Num AMQ"),
    s1HoOutDenomAmq: doublePrecision("S1 HO Out Denom AMQ"),
    "s1HoOut (%)Amq": doublePrecision("S1 HO Out (%) AMQ"),
    interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
    interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
    "interFreqLteHoSr_(%)Amq": doublePrecision("Inter Freq LTE HO SR_(%) AMQ"),
    interFreqX2HoNumAmq: doublePrecision("Inter Freq X2 HO Num AMQ"),
    interFreqX2HoDenumAmq: doublePrecision("Inter Freq X2 HO Denum AMQ"),
    "interFreqX2HoSr_(%)Amq": doublePrecision("Inter Freq X2 HO SR_(%) AMQ"),
    interFreqS1HoNumAmq: doublePrecision("Inter Freq S1 HO Num AMQ"),
    interFreqS1HoDenumAmq: doublePrecision("Inter Freq S1 HO Denum AMQ"),
    "interFreqS1HoSr_(%)Amq": doublePrecision("Inter Freq S1 HO SR_(%) AMQ"),
    lteUmtsHoNumAmq: doublePrecision("LTE-UMTS HO Num AMQ"),
    lteUmtsHoDenumAmq: doublePrecision("LTE-UMTS HO Denum AMQ"),
    "lteUmtsHoSr_(%)Amq": doublePrecision("LTE-UMTS HO SR_(%) AMQ"),
    lteGsmHoNumAmq: doublePrecision("LTE-GSM HO Num AMQ"),
    lteGsmHoDenumAmq: doublePrecision("LTE-GSM HO Denum AMQ"),
    "lteGsmHoSr_(%)Amq": doublePrecision("LTE-GSM HO SR_(%) AMQ"),
    userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
    userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
    "userDlThroughput (kbps)Amq": doublePrecision("User DL Throughput (Kbps) AMQ"),
    userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
    userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
    "userUlThroughput (kbps)Amq": doublePrecision("User UL Throughput (Kbps) AMQ"),
    cellDlThroughputNumAmq: doublePrecision("Cell DL Throughput Num AMQ"),
    cellDlThroughputDenumAmq: doublePrecision("Cell DL Throughput Denum AMQ"),
    "cellDlThroughput (kbps)Amq": doublePrecision("Cell DL Throughput (Kbps) AMQ"),
    cellUlThroughputNumAmq: doublePrecision("Cell UL Throughput Num AMQ"),
    cellUlThroughputDenumAmq: doublePrecision("Cell UL Throughput Denum AMQ"),
    "cellUlThroughput (kbps)Amq": doublePrecision("Cell UL Throughput (Kbps) AMQ"),
    "cqi>=7NumAmq": doublePrecision("CQI>=7 Num AMQ"),
    "cqi>=7DenumAmq": doublePrecision("CQI>=7 Denum AMQ"),
    "cqi>=7_(%)Amq": doublePrecision("CQI>=7_(%) AMQ"),
    cqiAverageAmq: doublePrecision("CQI Average AMQ"),
    ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
    ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
    "ulPrbUtilization_(%)Amq": doublePrecision("UL PRB Utilization_(%) AMQ"),
    dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
    dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
    "dlPrbUtilization_(%)Amq": doublePrecision("DL PRB Utilization_(%) AMQ"),
    ulRbAvailableAmq: doublePrecision("UL RB Available AMQ"),
    dlRbAvailableAmq: doublePrecision("DL RB Available AMQ"),
    "maximumNumberOfRrcConnectionUser(unit)": doublePrecision("Maximum Number of RRC Connection User(unit)"),
    "licenseNumberOfRrcConnectionUser (cell)": doublePrecision("License Number of RRC Connection User (Cell)"),
    averageNumberOfUeThatCanBeSimultaneously: doublePrecision("Average Number of UE that can be simultaneously"),
    maximumNumberOfUeThatCanBeSimultaneously: doublePrecision("Maximum Number of UE that can be simultaneously"),
    numberOfPagingRecordsReceivedByTheENodeB: doublePrecision("Number of Paging Records Received by the eNodeB"),
    "numberOfRedirectionRequestsFromLteToUtran(csfb)": doublePrecision(
      "Number of Redirection Requests from LTE to UTRAN(CSFB)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(csfb)(times)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(CSFB)(times)",
    ),
    "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
    "maximumNiOfCarrier(dBm)": doublePrecision("Maximum NI of Carrier(dBm)"),
    "maximumCellDlRlcThroughput(mbps)": doublePrecision("Maximum Cell DL RLC Throughput(Mbps)"),
    "maximumCellUlRlcThroughput(mbps)": doublePrecision("Maximum Cell UL RLC Throughput(Mbps)"),
    "maximumCellDlPdcpThroughput(mbps)": doublePrecision("Maximum Cell DL PDCP Throughput(Mbps)"),
    "maximumCellUlPdcpThroughput(mbps)": doublePrecision("Maximum Cell UL PDCP Throughput(Mbps)"),
    "dlPayloadCa_(mByte)Amq": doublePrecision("DL Payload CA_(MByte) AMQ"),
    "ulPayloadCa_(mByte)Amq": doublePrecision("UL Payload CA_(MByte) AMQ"),
    "totalPayloadCa_(mByte)Amq": doublePrecision("Total Payload CA_(MByte) AMQ"),
    dlThroughputCaNumAmq: doublePrecision("DL Throughput CA Num AMQ"),
    dlThroughputCaDenumAmq: doublePrecision("DL Throughput CA Denum AMQ"),
    "dlThroughputCa_(kbps)Amq": doublePrecision("DL Throughput CA_(kbps) AMQ"),
    ulThroughputCaNumAmq: doublePrecision("UL Throughput CA Num AMQ"),
    ulThroughputCaDenumAmq: doublePrecision("UL Throughput CA Denum AMQ"),
    "ulThroughputCa_(kbps)Amq": doublePrecision("UL Throughput CA_(kbps) AMQ"),
    numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
    denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
    "serviceDropRate (%)Amq": doublePrecision("Service Drop Rate (%) AMQ"),
    newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
    "u31_[lte]meanRrcConnectedUserNumber": doublePrecision("U31_[LTE]MeanRrcConnectedUserNUmber"),
    u31RatioOfRrcReEstablishment: doublePrecision("U31_Ratio of RRC Re-establishment "),
    "s1SignalConnectionEstablishmentSuccessRate(%)": doublePrecision(
      "S1-Signal Connection Establishment Success Rate(%)",
    ),
    "dlQpskModulationSchemeUsage(%)": doublePrecision("DL QPSK Modulation Scheme Usage(%)"),
    "dl16QamModulationSchemeUsage(%)": doublePrecision("DL 16QAM Modulation Scheme Usage(%)"),
    "dl64QamModulationSchemeUsage(%)": doublePrecision("DL 64QAM Modulation Scheme Usage(%)"),
    "dl256QamModulationSchemeUsage(%)": doublePrecision("DL 256QAM Modulation Scheme Usage(%)"),
    "ulQpskModulationSchemeUsage(%)": doublePrecision("UL QPSK Modulation Scheme Usage(%)"),
    "ul16QamModulationSchemeUsage(%)": doublePrecision("UL 16QAM Modulation Scheme Usage(%)"),
    "ul64QamModulationSchemeUsage(%)": doublePrecision("UL 64QAM Modulation Scheme Usage(%)"),
    "pagingCongestionRate(%)": doublePrecision("Paging Congestion Rate(%)"),
    "kpiPagingSuccessRate (%)": doublePrecision("KPI Paging Success Rate (%)"),
    u31AverageDlPdcpSduDelay: doublePrecision("U31_Average DL PDCP SDU Delay"),
    "averageDlIpPacketDelay(ms)": doublePrecision("Average DL IP Packet Delay(ms)"),
    "trafficVoLte_(erl)Amq": doublePrecision("Traffic_VoLTE_(erl) AMQ"),
    "u31_[lte]ipLatency": doublePrecision("U31_[LTE]IP Latency"),
    "cellUplinkInitBler(%)": doublePrecision("Cell Uplink Init BLER(%)"),
    "cellDownlinkInitBler(%)": doublePrecision("Cell Downlink Init BLER(%)"),
    averageDlActiveUserNumber: doublePrecision("Average DL Active User Number"),
    "dlAggregatedTimeForIpThroughput(ms)": doublePrecision("DL Aggregated Time For IP Throughput(ms)"),
    "dlAggregatedTime(ms)": doublePrecision("DL Aggregated Time(ms)"),
    prbNumberUsedOnPdschChannel: doublePrecision("PRB Number Used on PDSCH Channel"),
    numberOfCqi11BeUsed: doublePrecision("Number of CQI11 Be Used"),
    numberOfCqi12BeUsed: doublePrecision("Number of CQI12 Be Used"),
    numberOfCqi13BeUsed: doublePrecision("Number of CQI13 Be Used"),
    numberOfCqi14BeUsed: doublePrecision("Number of CQI14 Be Used"),
    numberOfCqi15BeUsed: doublePrecision("Number of CQI15 Be Used"),
    "dlVolumeVoLteQci1_(mByte)Amq": doublePrecision("DL_Volume_VoLTE_QCI1_(MByte) AMQ"),
    "ulVolumeVoLteQci1_(mByte)Amq": doublePrecision("UL_Volume_VoLTE_QCI1_(MByte) AMQ"),
    rrcEstablishmentVoLteNumAmq: doublePrecision("RRC_Establishment_VoLTE_Num AMQ"),
    rrcEstablishmentVoLteDenumAmq: doublePrecision("RRC_Establishment_VoLTE_Denum AMQ"),
    "rrcEstablishmentVoLteSr_(%)Amq": doublePrecision("RRC_Establishment_VoLTE_SR_(%) AMQ"),
    eRabSetupVoLteQci1NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Num AMQ"),
    eRabSetupVoLteQci1DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI1_Denum AMQ"),
    "eRabSetupVoLteQci1Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI1_SR_(%) AMQ"),
    eRabSetupVoLteQci5NumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Num AMQ"),
    eRabSetupVoLteQci5DenumAmq: doublePrecision("E-RAB_Setup_VoLTE_QCI5_Denum AMQ"),
    "eRabSetupVoLteQci5Sr_(%)Amq": doublePrecision("E-RAB_Setup_VoLTE_QCI5_SR_(%) AMQ"),
    callSetupVoLteNumAmq: doublePrecision("Call_Setup_VoLTE_Num AMQ"),
    callSetupVoLteDenumAmq: doublePrecision("Call_Setup_VoLTE_Denum AMQ"),
    "callSetupVoLteSr_(%)Amq": doublePrecision("Call_Setup_VoLTE_SR_(%) AMQ"),
    callDropVoLteNumAmq: doublePrecision("Call_Drop_VoLTE_Num AMQ"),
    callDropVoLteDenumAmq: doublePrecision("Call_Drop_VoLTE_Denum AMQ"),
    "callDropVoLteRate_(%)Amq": doublePrecision("Call_Drop_VoLTE_Rate_(%) AMQ"),
    intraFreqHosrVoLteNumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Num AMQ"),
    intraFreqHosrVoLteDenumAmq: doublePrecision("Intra_Freq_HOSR_VoLTE_Denum AMQ"),
    "intraFreqHosrVoLteSr_(%)Amq": doublePrecision("Intra_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    interFreqHosrVoLteNumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Num AMQ"),
    interFreqHosrVoLteDenumAmq: doublePrecision("Inter_Freq_HOSR_VoLTE_Denum AMQ"),
    "interFreqHosrVoLteSr_(%)Amq": doublePrecision("Inter_Freq_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteUmtsHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Num AMQ"),
    srvccLteUmtsHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_Denum AMQ"),
    "srvccLteUmtsHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-UMTS_HOSR_VoLTE_SR_(%) AMQ"),
    srvccLteGsmHosrVoLteNumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Num AMQ"),
    srvccLteGsmHosrVoLteDenumAmq: doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_Denum AMQ"),
    "srvccLteGsmHosrVoLteSr_(%)Amq": doublePrecision("SRVCC_LTE-GSM_HOSR_VoLTE_SR_(%) AMQ"),
    dlPdcpSduLossQci1NumAmq: doublePrecision("DL_PDCP_SDU_Loss_QCI1_Num AMQ"),
    dlPdcpSduLossQci1DenumAmq: doublePrecision("DL_PDCP_SDU_Loss_QCI1_Denum AMQ"),
    "dlPdcpSduLossQci1_(%)Amq": doublePrecision("DL_PDCP_SDU_Loss_QCI1_(%) AMQ"),
    ulPdcpSduLossQci1NumAmq: doublePrecision("UL_PDCP_SDU_Loss_QCI1_Num AMQ"),
    ulPdcpSduLossQci1DenumAmq: doublePrecision("UL_PDCP_SDU_Loss_QCI1_Denum AMQ"),
    "ulPdcpSduLossQci1_(%)Amq": doublePrecision("UL_PDCP_SDU_Loss_QCI1_(%) AMQ"),
    maxDlActiveUserNumberQci1Amq: doublePrecision("Max_DL_Active_User_Number_QCI1 AMQ"),
    maxUlActiveUserNumberQci1Amq: doublePrecision("Max_UL_Active_User_Number_QCI1 AMQ"),
    avgDlActiveUserNumberQci1Amq: doublePrecision("Avg_DL_Active_User_Number_QCI1 AMQ"),
    avgUlActiveUserNumberQci1Amq: doublePrecision("Avg_UL_Active_User_Number_QCI1 AMQ"),
    maxUserVoLteAmq: doublePrecision("Max_User_VoLTE AMQ"),
    "averageCellRssi(dBm)": doublePrecision("Average Cell RSSI(dBm)"),
    spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
    spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
    spectrumEfficiency: doublePrecision("spectrum efficiency"),
    "averageCpuUtilizationRateOfTheBasebandControlPlane(%)": doublePrecision(
      "Average CPU Utilization Rate of the Baseband Control-Plane(%)",
    ),
    "peakCpuUtilizationRateOfTheBasebandControlPlane(%)": doublePrecision(
      "Peak CPU Utilization Rate of the Baseband Control-Plane(%)",
    ),
    "numberOfRedirectionRequestsFromLteToGsm(dueToA2Event)": doublePrecision(
      "Number of Redirection Requests from LTE to GSM(Due to A2 event)",
    ),
    "numberOfRedirectionRequestsIntraRat(dueToInterFrequence": doublePrecision(
      "Number of Redirection Requests intra RAT(Due to inter-Frequence",
    ),
    throughputDistributionNum: doublePrecision("Throughput Distribution Num"),
    throughputDistributionDenum: doublePrecision("Throughput Distribution Denum"),
    averageCqiRev: doublePrecision("Average CQI_Rev"),
    numAverageCqiRev: doublePrecision("Num Average CQI_Rev"),
    denumAverageCqiRev: doublePrecision("Denum Average CQI_Rev"),
  },
  (table) => [
    index("idx_measdy4g_begin_time").using("btree", table.beginTime.asc().nullsLast().op("timestamp_ops")),
    index("idx_view4g_composite").using(
      "btree",
      table.beginTime.asc().nullsLast().op("float8_ops"),
      table.subnetWorkId.asc().nullsLast().op("timestamp_ops"),
      table.managedElementId.asc().nullsLast().op("timestamp_ops"),
      table.eNodeBid.asc().nullsLast().op("timestamp_ops"),
      table.cellId.asc().nullsLast().op("timestamp_ops"),
    ),
  ],
);

export const measTa4G62Counter = pgTable(
  "measTA4G62Counter",
  {
    beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
    endTime: time("End Time"),
    granularity: varchar("Granularity", { length: 255 }),
    subnetWorkId: integer("SubnetWork ID").notNull(),
    subnetWorkName: varchar("SubnetWork Name", { length: 255 }),
    managedElementId: integer("ManagedElement ID").notNull(),
    "managed element": varchar("Managed Element", { length: 255 }),
    eNodeBId: varchar("eNodeB ID", { length: 255 }),
    eNodeBName: varchar("eNodeB Name", { length: 255 }),
    "eUtran fdd cellId": varchar("E-UTRAN FDD Cell ID", { length: 255 }),
    "eUtran fdd cellName": varchar("E-UTRAN FDD Cell Name", { length: 255 }),
    eNodeBid: integer().notNull(),
    cellId: integer().notNull(),
    "reservedCounter183(times)": integer("Reserved Counter 183(times)"),
    "reservedCounter184(times)": integer("Reserved Counter 184(times)"),
    "reservedCounter185(times)": integer("Reserved Counter 185(times)"),
    "reservedCounter186(times)": integer("Reserved Counter 186(times)"),
    "reservedCounter187(times)": integer("Reserved Counter 187(times)"),
    "reservedCounter188(times)": integer("Reserved Counter 188(times)"),
    "reservedCounter189(times)": integer("Reserved Counter 189(times)"),
    "reservedCounter190(times)": integer("Reserved Counter 190(times)"),
    "reservedCounter191(times)": integer("Reserved Counter 191(times)"),
    "reservedCounter192(times)": integer("Reserved Counter 192(times)"),
    "reservedCounter193(times)": integer("Reserved Counter 193(times)"),
    "reservedCounter194(times)": integer("Reserved Counter 194(times)"),
    "reservedCounter195(times)": integer("Reserved Counter 195(times)"),
    "reservedCounter196(times)": integer("Reserved Counter 196(times)"),
    "reservedCounter197(times)": integer("Reserved Counter 197(times)"),
    "reservedCounter198(times)": integer("Reserved Counter 198(times)"),
    "reservedCounter199(times)": integer("Reserved Counter 199(times)"),
    "reservedCounter200(times)": integer("Reserved Counter 200(times)"),
    "reservedCounter201(times)": integer("Reserved Counter 201(times)"),
    "reservedCounter202(times)": integer("Reserved Counter 202(times)"),
    "reservedCounter203(times)": integer("Reserved Counter 203(times)"),
    "reservedCounter204(times)": integer("Reserved Counter 204(times)"),
    "reservedCounter205(times)": integer("Reserved Counter 205(times)"),
    "reservedCounter206(times)": integer("Reserved Counter 206(times)"),
    "reservedCounter207(times)": integer("Reserved Counter 207(times)"),
    "reservedCounter208(times)": integer("Reserved Counter 208(times)"),
    "reservedCounter209(times)": integer("Reserved Counter 209(times)"),
    "reservedCounter210(times)": integer("Reserved Counter 210(times)"),
    "reservedCounter211(times)": integer("Reserved Counter 211(times)"),
    "reservedCounter212(times)": integer("Reserved Counter 212(times)"),
    "reservedCounter213(times)": integer("Reserved Counter 213(times)"),
    "reservedCounter214(times)": integer("Reserved Counter 214(times)"),
    "reservedCounter215(times)": integer("Reserved Counter 215(times)"),
    "reservedCounter216(times)": integer("Reserved Counter 216(times)"),
    "reservedCounter217(times)": integer("Reserved Counter 217(times)"),
    "reservedCounter218(times)": integer("Reserved Counter 218(times)"),
    "reservedCounter219(times)": integer("Reserved Counter 219(times)"),
    "reservedCounter220(times)": integer("Reserved Counter 220(times)"),
    "reservedCounter221(times)": integer("Reserved Counter 221(times)"),
    "reservedCounter222(times)": integer("Reserved Counter 222(times)"),
    "reservedCounter223(times)": integer("Reserved Counter 223(times)"),
    "reservedCounter224(times)": integer("Reserved Counter 224(times)"),
    "reservedCounter225(times)": integer("Reserved Counter 225(times)"),
    "reservedCounter226(times)": integer("Reserved Counter 226(times)"),
    "reservedCounter227(times)": integer("Reserved Counter 227(times)"),
    "reservedCounter228(times)": integer("Reserved Counter 228(times)"),
    "reservedCounter229(times)": integer("Reserved Counter 229(times)"),
    "reservedCounter230(times)": integer("Reserved Counter 230(times)"),
    "reservedCounter231(times)": integer("Reserved Counter 231(times)"),
    "reservedCounter232(times)": integer("Reserved Counter 232(times)"),
    "reservedCounter233(times)": integer("Reserved Counter 233(times)"),
    "reservedCounter234(times)": integer("Reserved Counter 234(times)"),
    "reservedCounter235(times)": integer("Reserved Counter 235(times)"),
    "reservedCounter236(times)": integer("Reserved Counter 236(times)"),
    "reservedCounter237(times)": integer("Reserved Counter 237(times)"),
    "reservedCounter238(times)": integer("Reserved Counter 238(times)"),
    "reservedCounter239(times)": integer("Reserved Counter 239(times)"),
    "reservedCounter240(times)": integer("Reserved Counter 240(times)"),
    "reservedCounter241(times)": integer("Reserved Counter 241(times)"),
    "reservedCounter242(times)": integer("Reserved Counter 242(times)"),
    "reservedCounter243(times)": integer("Reserved Counter 243(times)"),
    "reservedCounter244(times)": integer("Reserved Counter 244(times)"),
    "maximumOfTaValue(16Ts)": integer("Maximum of TA Value(16Ts)"),
    "numberOfUplinkStateFromSynToAsyn(times)": integer("Number of Uplink State from Syn to Asyn(times)"),
    "totalTimeOfUplinkAsynState(ms)": integer("Total Time of Uplink Asyn State(ms)"),
    "0078": doublePrecision("0.078"),
    "0156": doublePrecision("0.156"),
    "0234": doublePrecision("0.234"),
    "0312": doublePrecision("0.312"),
    "039": doublePrecision("0.39"),
    "0468": doublePrecision("0.468"),
    "0546": doublePrecision("0.546"),
    "0624": doublePrecision("0.624"),
    "0702": doublePrecision("0.702"),
    "078": doublePrecision("0.78"),
    "0858": doublePrecision("0.858"),
    "0936": doublePrecision("0.936"),
    "1014": doublePrecision("1.014"),
    "1092": doublePrecision("1.092"),
    "117": doublePrecision("1.17"),
    "1248": doublePrecision("1.248"),
    "1326": doublePrecision("1.326"),
    "1404": doublePrecision("1.404"),
    "1482": doublePrecision("1.482"),
    "156": doublePrecision("1.56"),
    "1638": doublePrecision("1.638"),
    "1716": doublePrecision("1.716"),
    "1794": doublePrecision("1.794"),
    "1872": doublePrecision("1.872"),
    "195": doublePrecision("1.95"),
    "2028": doublePrecision("2.028"),
    "2106": doublePrecision("2.106"),
    "2184": doublePrecision("2.184"),
    "2262": doublePrecision("2.262"),
    "234": doublePrecision("2.34"),
    "2418": doublePrecision("2.418"),
    "2496": doublePrecision("2.496"),
    "2574": doublePrecision("2.574"),
    "2652": doublePrecision("2.652"),
    "273": doublePrecision("2.73"),
    "2808": doublePrecision("2.808"),
    "2886": doublePrecision("2.886"),
    "2964": doublePrecision("2.964"),
    "3042": doublePrecision("3.042"),
    "312": doublePrecision("3.12"),
    "3198": doublePrecision("3.198"),
    "3276": doublePrecision("3.276"),
    "3354": doublePrecision("3.354"),
    "3432": doublePrecision("3.432"),
    "351": doublePrecision("3.51"),
    "3588": doublePrecision("3.588"),
    "4212": doublePrecision("4.212"),
    "4836": doublePrecision("4.836"),
    "546": doublePrecision("5.46"),
    "6084": doublePrecision("6.084"),
    "6708": doublePrecision("6.708"),
    "7488": doublePrecision("7.488"),
    "8268": doublePrecision("8.268"),
    "9048": doublePrecision("9.048"),
    "9828": doublePrecision("9.828"),
    "10608": doublePrecision("10.608"),
    "11388": doublePrecision("11.388"),
    "12168": doublePrecision("12.168"),
    "12948": doublePrecision("12.948"),
    "13728": doublePrecision("13.728"),
    "14508": doublePrecision("14.508"),
    ">15Km": integer(">15 KM"),
    siteid: varchar("SITEID", { length: 255 }),
    siteCi: varchar("site_CI", { length: 255 }),
    "index90%": integer("Index 90%"),
    "ta90%": doublePrecision("TA 90%"),
    sec: integer("SEC"),
    siteSec: varchar("SITE_SEC", { length: 255 }),
    "%taIn1Km": doublePrecision("%TA in 1km"),
    "isdCellKm (lookup)": doublePrecision("ISD cell km (lookup)"),
    isdCellConvert: doublePrecision("ISD cell convert"),
    "%ta <Isd (index)": integer("%TA < ISD (index)"),
    "%ta <Isd (%)": doublePrecision("%TA <  ISD (%)"),
    "%ta >Isd (%)": doublePrecision("%TA > ISD (%)"),
    overshootRemark: varchar("Overshoot remark", { length: 255 }),
    "index70%": integer("Index 70%"),
    "ta70%": doublePrecision("TA 70%"),
    overtiltRemark: varchar("Overtilt remark", { length: 255 }),
    "isdCell /2": doublePrecision("ISD cell /2"),
    "isdCell /2Convert": doublePrecision("ISD cell /2 convert"),
    "%ta <Isd/2 (index)": integer("%TA < ISD/2 (index)"),
    "%ta <Isd/2 (%)": doublePrecision("%TA <  ISD/2 (%)"),
    "%ta >Isd (%)1": doublePrecision("%TA > ISD (%)1"),
    tooMuchOverlapRemark: varchar("Too much overlap remark", { length: 255 }),
    combine: varchar("Combine", { length: 255 }),
    kabupaten: varchar("Kabupaten", { length: 255 }),
  },
  (table) => [
    index("idx_measta4g62counter_composite").using(
      "btree",
      table.subnetWorkId.asc().nullsLast().op("int4_ops"),
      table.managedElementId.asc().nullsLast().op("int4_ops"),
      table.eNodeBid.asc().nullsLast().op("int4_ops"),
      table.cellId.asc().nullsLast().op("int4_ops"),
    ),
  ],
);

export const measHy4G = pgTable("measHy4g", {
  beginTime: timestamp("Begin Time", {
    precision: 6,
    mode: "string",
  }).notNull(),
  subnetWorkId: doublePrecision("SubnetWork ID").notNull(),
  subnetWorkName: varchar("SubnetWork Name", { length: 200 }),
  managedElementId: doublePrecision("ManagedElement ID").notNull(),
  "managed element": varchar("Managed Element", { length: 200 }),
  eNodeBName: varchar("eNodeB Name", { length: 200 }),
  cellName: varchar("Cell Name", { length: 200 }),
  eNodeBid: doublePrecision().notNull(),
  cellId: doublePrecision().notNull(),
  "4GPayload (mByte)Amq": doublePrecision("4G Payload (MByte) AMQ"),
  cellAvailabilityNum4GAmq: doublePrecision("Cell Availability Num 4G AMQ"),
  cellAvailabilityDenum4GAmq: doublePrecision("Cell Availability Denum 4G AMQ"),
  numRrcSetupSrAmq: doublePrecision("Num RRC Setup SR AMQ"),
  denumRrcSetupSrAmq: doublePrecision("Denum RRC Setup SR AMQ"),
  numERabSetupSrAmq: doublePrecision("Num E-RAB Setup SR AMQ"),
  denumERabSetupSrAmq: doublePrecision("Denum E-RAB Setup SR AMQ"),
  numCssrAmq: doublePrecision("Num CSSR AMQ"),
  denumCssrAmq: doublePrecision("Denum CSSR AMQ"),
  numERabDropAmq: doublePrecision("Num E-RAB Drop AMQ"),
  denumERabDropAmq: doublePrecision("Denum E-RAB Drop AMQ"),
  numIfhoSrAmq: doublePrecision("Num IFHO SR AMQ"),
  denumIfhoSrAmq: doublePrecision("Denum IFHO SR AMQ"),
  interFreqLteHoNumAmq: doublePrecision("Inter Freq LTE HO Num AMQ"),
  interFreqLteHoDenumAmq: doublePrecision("Inter Freq LTE HO Denum AMQ"),
  userDlThroughputNumAmq: doublePrecision("User DL Throughput Num AMQ"),
  userDlThroughputDenumAmq: doublePrecision("User DL Throughput Denum AMQ"),
  userUlThroughputNumAmq: doublePrecision("User UL Throughput Num AMQ"),
  userUlThroughputDenumAmq: doublePrecision("User UL Throughput Denum AMQ"),
  cqiAverageAmq: doublePrecision("CQI Average AMQ"),
  ulPrbUtilizationNumAmq: doublePrecision("UL PRB Utilization Num AMQ"),
  ulPrbUtilizationDenumAmq: doublePrecision("UL PRB Utilization Denum AMQ"),
  dlPrbUtilizationNumAmq: doublePrecision("DL PRB Utilization Num AMQ"),
  dlPrbUtilizationDenumAmq: doublePrecision("DL PRB Utilization Denum AMQ"),
  maximumNumberOfRrcConnectionUser: doublePrecision("Maximum Number of RRC Connection User"),
  "averageNiOfCarrier(dBm)": doublePrecision("Average NI of Carrier(dBm)"),
  numServiceDropRateAmq: doublePrecision("Num Service Drop Rate AMQ"),
  denumServiceDropRateAmq: doublePrecision("Denum Service Drop Rate AMQ"),
  newActiveUsersRnpOno: doublePrecision("New Active Users rnp_Ono"),
  spectrumEfficiencyNum: doublePrecision("spectrum efficiency num"),
  spectrumEfficiencyDenum: doublePrecision("spectrum efficiency denum"),
  spectrumEfficiency: doublePrecision("spectrum efficiency"),
  throughputDistributionNum: doublePrecision("Throughput Distribution Num"),
  throughputDistributionDenum: doublePrecision("Throughput Distribution Denum"),
});

export const measDy2G = pgTable("measDy2g", {
  beginTime: timestamp("Begin Time", { mode: "string" }).notNull(),
  subnetWorkId: doublePrecision("SubnetWork ID").notNull(),
  subnetWorkName: varchar("SubnetWork Name", { length: 200 }),
  managedElementId: doublePrecision("ManagedElement ID").notNull(),
  managedElement: varchar("Managed Element", { length: 200 }),
  siteId: doublePrecision("SITE ID").notNull(),
  siteName: varchar("SITE Name", { length: 200 }),
  btsId: doublePrecision("BTS ID").notNull(),
  btsName: varchar("BTS Name", { length: 200 }),
  nodeBName: varchar("NodeB Name", { length: 200 }),
  locationAreaCode: doublePrecision("Location Area Code").notNull(),
  cellIdentity: doublePrecision("Cell Identity").notNull(),
  "tchTraffic (erl)Ono": doublePrecision("TCH Traffic (Erl)_ono"),
  "gprsPayload (mbyte)Ono": doublePrecision("GPRS Payload (Mbyte)_ono"),
  "edgePayload (mbyte)Ono": doublePrecision("EDGE Payload (Mbyte)_ono"),
  "sdcchTraffic (erl)Ono": doublePrecision("SDCCH Traffic (Erl)_ono"),
  "tchBlockingRate (%)Ono": doublePrecision("TCH Blocking Rate (%)_ono"),
  "sdsr (%)Ono": doublePrecision("SDSR (%)_ono"),
  "tbfDlEstSr (%)Ono": doublePrecision("TBF_DL Est_SR (%)_ono"),
  "tchDropRate (%)Ono": doublePrecision("TCH Drop Rate (%)_ono"),
  "tbfCompletionSr (%)Ono": doublePrecision("TBF Completion_SR (%)_ono"),
  "hosr (%)Ono": doublePrecision("HOSR (%)_ono"),
  "tchAvailability (%)Ono": doublePrecision("TCH Availability (%)_Ono"),
  numTchAvailabilityOno: doublePrecision("Num TCH Availability_Ono"),
  denumTchAvailabilityOno: doublePrecision("Denum TCH Availability_ono"),
  tchDropNumOno: doublePrecision("TCH_Drop_num_ono"),
  tchDropDenumOno: doublePrecision("TCH_Drop_denum_ono"),
  tchBlockNumOno: doublePrecision("TCH_Block_num_ono"),
  tchBlockDenumOno: doublePrecision("TCH_Block_denum_ono"),
  hosrNumOno: doublePrecision("HOSR_num_ono"),
  hosrDenumOno: doublePrecision("HOSR_denum_ono"),
  sdsrNumOno: doublePrecision("SDSR_num_ono"),
  sdsrDenumOno: doublePrecision("SDSR_denum_ono"),
  numTbfDlEstSrNfj1513202618039017: doublePrecision("Num TBF DL Est SR NFJ_1513202618039-0-17"),
  denumTbfDlEstSrNfj1513202618039018: doublePrecision("Denum TBF DL Est SR NFJ_1513202618039-0-18"),
  numTbfCompSrNfj1513202618039023: doublePrecision("Num TBF Comp SR NFJ_1513202618039-0-23"),
  denumTbfCompSrNfj1513202618039024: doublePrecision("Denum TBF Comp SR NFJ_1513202618039-0-24"),
  "sdcchBlockingRate (%)Ono": doublePrecision("SDCCH Blocking Rate (%)_ono"),
  sdcchBlockNumOno: doublePrecision("SDCCH_Block_num_ono"),
  sdcchBlockDenumOno: doublePrecision("SDCCH_Block_denum_ono"),
  numberOfTrx: doublePrecision("Number of TRX"),
  numberOfTch: doublePrecision("Number of TCH"),
  numberOfSdcch: doublePrecision("Number of SDCCH"),
  numberOfStaticPdtch: doublePrecision("Number of Static PDTCH"),
  numberOfDynamicPdtch: doublePrecision("Number of dynamic PDTCH"),
  numDlQual05Ono: doublePrecision("Num DL Qual 0-5_ono"),
  denumDlQual05Ono: doublePrecision("Denum DL Qual 0-5_Ono"),
  "dlQual05 (%)Ono": doublePrecision("DL Qual 0-5 (%)_Ono"),
  numUlQual05Ono: doublePrecision("Num UL Qual 0-5_Ono"),
  denumUlQual05Ono: doublePrecision("Denum UL Qual 0-5_Ono"),
  "ulQual05 (%)Ono": doublePrecision("UL Qual 0-5 (%)_Ono"),
  numIcmInterferenceOno: doublePrecision("Num ICM INTERFERENCE_Ono"),
  denumIcmInterferenceOno: doublePrecision("Denum ICM INTERFERENCE_ono"),
  "icmInterference (%)Ono": doublePrecision("ICM_INTERFERENCE (%)_Ono"),
  numTbfUlEstSrNfj1513202618039020: doublePrecision("Num TBF UL Est SR NFJ_1513202618039-0-20"),
  denumTbfUlEstSrNfj1513202618039021: doublePrecision("Denum TBF UL Est SR NFJ_1513202618039-0-21"),
  "tbfUlEstSr (%)Ono": doublePrecision("TBF_UL Est_SR (%)_ono"),
  "gprsDlThroughput (kbps)Ono": doublePrecision("GPRS DL_Throughput (kbps)_ono"),
  "edgeDlThroughput (kbps)Ono": doublePrecision("EDGE DL_Throughput (kbps)_ono"),
  "tchHrTraffic (erl)Ono": doublePrecision("TCH HR Traffic (Erl)_ono"),
  "tchFrTraffic (erl)Ono": doublePrecision("TCH FR Traffic (Erl)_ono"),
  numberOfFastreturnToUtran: doublePrecision("Number of fastreturn to UTRAN"),
  numberOfFastreturnToLte: doublePrecision("Number of fastreturn to LTE"),
  dlEmiOno: doublePrecision("DL_EMI_Ono"),
  dlEmiNumOno: doublePrecision("DL_EMI_Num_Ono"),
  dlEmiDenumOno: doublePrecision("DL_EMI_Denum_Ono"),
  ulEmiOno: doublePrecision("UL_EMI_Ono"),
  ulEmiNumOno: doublePrecision("UL_EMI_Num_Ono"),
  ulEmiDenumOno: doublePrecision("UL_EMI_Denum_Ono"),
  "sdToTchSuccessRate (%)": doublePrecision("SD to TCH Success Rate (%)"),
  dataIntegrity: doublePrecision("Data Integrity"),
});
